# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.4"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install flake8 coveralls coverage nose yanc
  - easy_install .

# command to run tests, e.g. python setup.py test
script:
  - nosetests tests --with-yanc --with-coverage --cover-package=onebot
  - make lint

after_success: coveralls
